### ISSUE TITLE
Next Gen Music Player

### ISSUE THREAD

**Issue by Nine-H** [elementary/music#105]
Dan declared noise dead* this arvo on reddit, which was pretty upsetting because I've been making pull requests, and it's the only app I've opened every single day. However, I figure that gives me carte blanche to make sweeping changes and delete as much awful code as I feel like because, if it's probably going to get the chop by April, why the hell not?

edit: probably dead https://www.reddit.com/r/elementaryos/comments/7gbxpw/whats_the_next_big_evolution_feature_that/dqilem4/

**Here's my kill list:**

- cmake build: I want to learn meson for my resume
- status bar: it just looks gross
- info panel: sucks, nobody uses last.fm anymore
- star ratings: if it's on my laptop then it's dope
- cd support: when was the last time you played a cd?
- ipod support: apple does not support ipods. let that sink in.
- as many dialogs as possible
- about 10,000 lines of code: it should be light, people should stop making classes and declaring variables
- plugin system: mpris should be built in
- code comments
- any feature that's not playing music or managing library + playlists

**And here's my glorious new regime:**

- drag and drop
- play zips
- masterfader on the EQ
- subtractive only EQ
- global bindable hotkeys for play/pause and skip
- album overlay instead of dialog
- edit tags in list view

I'm opening this bug to solicit graphic designs and hopefully get a sponsor from the core team to review my pull requests.

**Comment by Nine-H** [comment]
**killing cmake**

- there's way too much cmake
- project split into _core_ and _noise_
- it appears that _core_ is accessible by plugins and _noise_ is the interface

**Comment by Bat41** [comment]
Why did Daniel said he wanted to kill noise? Which music player will be shipped with elementary then?

**Comment by Nine-H** [comment]
cassidy has a player on his github, and I hope that's not what they mean.

**Comment by Nine-H** [comment]
I don't know, "stripped down" is very vague. I guess this is a candidate, but it's not really my kind of player https://github.com/cassidyjames/audio I'm sure dan will swing by this thread at some point.

**Comment by danrabbit** [comment]
Well I didn't say it was dead :p I said there's been some conversations around whether the time investment is worth it. Pull requests from both of you are super appreciated!

While I agree with a ton of things on your list, having a mega bug report like this isn't really trackable. It would be better to make individual reports and start a new Project board for discussions, mockups, etc.

I'm going to close this particular report as "invalid" just because it's a group report and not trackable, but please open up new issue reports with these items as individual tickets.

Also, if both of you would like to shoot me an email (daniel at elementary.io) I'll get you a Slack invite :)
