### ISSUE TITLE
The entire library is inserted into the queue by selecting a new song

### ISSUE THREAD

**Issue by michelinus** [elementary/music#438]
# Steps to reproduce the behavior
- Play any track in your library
- The entire library is inserted in the queue
- By changing the song the full library is inserted back in the queue again, added at the previous queue causing errors like this:

![First Screen](https://dumpshare.net/images/689476Schermatadel2018_10_1711.10.59.png)
Playing a song, the library is added to the queue
It's in italian, "Coda" is "Queue"

![Second Screen](https://dumpshare.net/images/1448123Schermatadel2018_10_1711.11.09.png)
Now the full queue is added again, and if you play another song, it is added again and again and it can reach very high numbers like this

![Third Screen](https://dumpshare.net/images/3023084Schermatadel2018_10_1711.17.04.png)

**Comment by eljefuri** [comment]
Just chiming in to say that this behavior definitely feels super strange.

**Comment by aljelly** [comment]
As noted in https://github.com/elementary/music/issues/442#issuecomment-433518927, even though it appears the whole library has been added to the queue, only the files you add actually play. So the actual queuing functionality in the background seems to be working fine. It would seem the problem is more to do with the UI.
