### ISSUE TITLE
Music app has a different accent color than the rest of the desktop

### ISSUE THREAD

**Issue by rokonxr** [elementary/music#582]

**Comment by cassidyjames** [comment]
This is intentional, as detailed in the [Hera release blog](https://blog.elementary.io/introducing-elementary-os-5-1-hera/#music). Apps can set a per-app accent color, much like what you see on other platforms like Android or Windows. For music, the playful orange matches its app icon. The Calendar app also uses this to set a green accent that matches its app icon as we detailed back in [February, 2019](https://blog.elementary.io/juno-updates-for-february-2019/#calendar).
