### ISSUE TITLE
missing icon for columns

### ISSUE THREAD

**Issue by ilippert** [elementary/music#640]
I run Music on Fedora 34, updated 24/5/21.

![missingimage](https://user-images.githubusercontent.com/20518297/120799987-bb3ed200-c53f-11eb-9a25-097c034ea2ce.png)

is the menu - so, the column view icon is missing.

**Comment by danrabbit** [comment]
It doesn't look like you're using elementary icons or the elementary stylesheet. The icon set you're using appears to be missing this icon. You can either file an issue against the icon set to include the icon or use the elementary icons, but this isn't really an issue in Music which expects these platform icons to be present

Closing as "Out of scope", since a missing icon is an issue in the icon set and not in Music
