### ISSUE TITLE
SmartPlaylist not updated until we restart application

### ISSUE THREAD

**Issue by mohansharma-me** [elementary/music#67]
Issue description:

1. First, I created one SmartPL with : Album contains word "ring"
![screenshot from 2017-09-06 12-21-12](https://user-images.githubusercontent.com/11788765/30098073-133ae64c-92fe-11e7-9c23-b5cd489db732.png)

2. You can see one music file listed there
![screenshot from 2017-09-06 12-21-29](https://user-images.githubusercontent.com/11788765/30098092-266516de-92fe-11e7-8a7d-f3ab4e37f7de.png)

3. After that I edited same SmartPL with : Album contains word "1920"
![screenshot from 2017-09-06 12-21-56](https://user-images.githubusercontent.com/11788765/30098115-3989eff0-92fe-11e7-8b37-665bf5735b0b.png)

4. So as you can see in below screenshot that new results is added with old results
![screenshot from 2017-09-06 12-22-13](https://user-images.githubusercontent.com/11788765/30098133-514dd124-92fe-11e7-8b9e-2d84f7086f6c.png)

5. But after restarting noise, old results gone.

**Comment by mohansharma-me** [comment]
Solution: after closing SmartPlaylistEditor we can reload that particular smartplaylist.

**Comment by pablojimpas** [comment]
This problem is no longer reproducible in `master` branch,  most likely it was fixed a few years ago...if anyone wants to bother to look at the history: https://github.com/elementary/music/commits/master/src/Dialogs/SmartPlaylistEditor.vala

So this issue should be closed to keep the issues board tidy.
