### ISSUE TITLE
music player themes?

### ISSUE THREAD

**Issue by mrlinuxdude** [elementary/music#721]
### Problem

I'm using the new music player and really love it. Trying to get my favorite theme numix-gtk-blue on it doesn't look right and no icons show up

### Proposal

will other themes work out of the box with this music player 7. or is there option to downgrade to the older version if we want other themes then elementary's

**Comment by danrabbit** [comment]
Music is built against the elementary stylesheet and icons and depends on the styles found there to look right. I've submitted a pull request to hard code the styles we require so that Music will still work correctly on non-elementary OS systems. It's not really feasible for us to support arbitrary stylesheets and icon libraries, sorry!

**Comment by mrlinuxdude** [comment]
Thanks for the request
