### ISSUE TITLE
Shortcuts improvements

### ISSUE THREAD

**Issue by diogopessoa** [elementary/music#727]
### Problem

Music does not allow to pause/resume or forward/backward the song with the shortcut. For this I have to first click on the application button for this.

### Proposal

With Music selected, alternatively use the following shortcuts instead of clicking the button to:

- the spacebar to pause/resume play

- left/right arrows for forward/backward

Thanks a lot for this project, it's really nice!

**Comment by danirabbit** [comment]
Thanks for your report! We wouldn't be able to use these keys without modifiers because it would interfere with keyboard navigation which would be an accessibility issue.

It's worth noting that we do support system media keys through MPRIS even when the app is not focused. If your keyboard doesn't have media keys, I believe you can assign custom shortcuts to media functions in System Settings → Keyboard → Shortcuts.

Let me know if that resolves your issue!
